### ISSUE TITLE
Invalid Request or Credentials

### ISSUE THREAD

**Issue by remusgondecjr** [fishbigger/HomeAssistant-Tapo-P100-Control#1]
Hi,

I'm trying to set this up for one of my Tapo P100 plugs but I get the following error:
"Exception: Error Code: -1501, Invalid Request or Credentials"

I'm sure that credentials are OK. I even tried changing my password, it works on the Tapo app, but not in home assistant.

**Comment by fishbigger** [comment]
Hey, does your password have any special characters in it? And have you tried a password reset in the app?

**Comment by remusgondecjr** [comment]
Yes, I did try a password reset in the app, but no luck. Tried different passwords, also without special characters but still no luck.

**Comment by manuelmann** [comment]
Hi,
I had the same issue, then I stumbled over following lines in switch.py:
starting at line 28
	ipAddress = config[CONF_IP_ADDRESS]
	email = config[CONF_EMAIL]
	password = config.get(CONF_PASSWORD)
After changing that to 
	ipAddress = config.get(CONF_IP_ADDRESS)
	email = config.get(CONF_EMAIL)
	password = config.get(CONF_PASSWORD)
it worked.

**Comment by niahane** [comment]
Same here

**Comment by rywi** [comment]
Same 

2020-12-03 17:18:20 ERROR (SyncWorker_1) [custom_components.tapo_p100_control.switch] Could not connect to plug. Possibly invalid credentials
2020-12-03 17:18:21 ERROR (MainThread) [homeassistant.components.switch] Error while setting up tapo_p100_control platform for switch
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/PyP100/PyP100.py", line 155, in login
self.token = ast.literal_eval(decryptedResponse)["result"]["token"]
KeyError: 'result'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 199, in _async_setup_platform
await asyncio.shield(task)
File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/tapo_p100_control/switch.py", line 41, in setup_platform
add_entities([P100Plug(p100)])
File "/config/custom_components/tapo_p100_control/switch.py", line 49, in __init__
self.update()
File "/config/custom_components/tapo_p100_control/switch.py", line 79, in update
self._p100.login()
File "/usr/local/lib/python3.8/site-packages/PyP100/PyP100.py", line 159, in login
raise Exception(f"Error Code: {errorCode}, {errorMessage}")
Exception: Error Code: -1501, Invalid Request or Credentials

**Comment by piio** [comment]
It looks like there is problem with passwords longer than 8 chars.

I also had a problem with Exception: Error Code: -1501, Invalid Request or Credentials with Tapo L510E bulb.

Firstly I got old firmware when I was configuring bulb on Tapo, after configuring it I upgraded to newest one - 1.1.7 Build 20201029 Rel. 40821

With this version I get -1051 error.

After that I changed password to 8-chars (was 12 chars previously) and verified again - nothing changes.
So I removed bulb from Tapo app and re-added it.
After this change the bulb started to work from HA.

**Comment by MrSleeps** [comment]
I've also been having the same issue with credentials not being valid.

Can confirm that removing and then adding the plug back into the app worked for me (also be careful you don't get yourself locked out of the account)..

The PHP library tp-link-info by jacobkossman doesn't have this issue..

**Comment by deangoldhill** [comment]
I also managed to get it working after some trial and error. And I think there are 2 issues here.
1 - It won't work with a password longer than 8 characters.
2 - the device needs to be removed and re-added to the app for the password change to take effect. This is what had me so confused!
I verified this by changing my password again, but HA continued to work having the old password in the config file. When I once again re-added the device, HA stopped working with the same 1051 error.

**Comment by addrum** [comment]
Just did the exact same. Changed password to 8 characters, and readded the plugs. They now show up as entities.
