### ISSUE TITLE
-1501, Invalid Request or Credentials is it broken?

### ISSUE THREAD

**Issue by ChokunPlayZ** [fishbigger/HomeAssistant-Tapo-P100-Control#33]
some of you might think that's it's my credentials that is the problem 
but I recheck already it works on TP-Link website and apps
here's the full error 

```
2021-07-30 21:19:08 ERROR (SyncWorker_1) [custom_components.tapo_p100_control.switch] Could not connect to plug. Possibly invalid credentials
2021-07-30 21:19:08 ERROR (MainThread) [homeassistant.components.switch] Error while setting up tapo_p100_control platform for switch
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/PyP100/PyP100.py", line 155, in login
    self.token = ast.literal_eval(decryptedResponse)["result"]["token"]
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 250, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/tapo_p100_control/switch.py", line 43, in setup_platform
    add_entities([P100Plug(p100)])
  File "/config/custom_components/tapo_p100_control/switch.py", line 52, in __init__
    self.update()
  File "/config/custom_components/tapo_p100_control/switch.py", line 83, in update
    self._p100.login()
  File "/usr/local/lib/python3.8/site-packages/PyP100/PyP100.py", line 159, in login
    raise Exception(f"Error Code: {errorCode}, {errorMessage}")
Exception: Error Code: -1501, Invalid Request or Credentials
```

I'm sure that my credentials isn't the problem

**Comment by mortyone** [comment]
I'm having the exact same issue on Home-Assistant 2021.7

I've taken a fresh copy of the component from github and also verified my credentials are correct by logging out/into the TP-Link Tapo app, but alas no joy...

Thanks

**Comment by ChokunPlayZ** [comment]
> 
> 
> I'm having the exact same issue on Home-Assistant 2021.7
> 
> I've taken a fresh copy of the component from github and also verified my credentials are correct by logging out/into the TP-Link Tapo app, but alas no joy...
> 
> Thanks

I change my tp-link ID password to exactly 8 letters, re-add the plug to tapo app restart HA and problem solved

**Comment by ChokunPlayZ** [comment]
The problem is now solved,

so this is the requirement
your password needs to be exactly 8 letters no more and no less

when you changed the password re-add the device to the Tapo app, reconfigure HA and restart it then you're good to go

**Comment by ChokunPlayZ** [comment]
The problem is now solved,

so this is the requirement
your password needs to be exactly 8 letters no more and no less

when you changed the password re-add the device to the Tapo app, reconfigure HA and restart it then you're good to go
