### ISSUE TITLE
Entity not available

### ISSUE THREAD

**Issue by marcopi** [fishbigger/HomeAssistant-Tapo-P100-Control#49]
Hi,
thanks for your work!! Really appreciated.
I tried latest version (as of commit 0d3193203d9b94901eaca8483942ddc945f33986) in HA but tapo switch is not available.
The stack trace from HA registry is:
```
Error while setting up tapo_p100_control platform for switch

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/tapo_p100_control/switch.py", line 44, in setup_platform
    add_entities([P100Plug(p100)])
  File "/config/custom_components/tapo_p100_control/switch.py", line 53, in __init__
    self.update()
  File "/config/custom_components/tapo_p100_control/switch.py", line 88, in update
    encodedName = data["result"]["nickname"]
TypeError: string indices must be integers
```
I ended up restoring the conversion from json to make it work:
```
diff --git a/tapo_p100_control/switch.py b/tapo_p100_control/switch.py
index 686fafe..ba4a959 100644
--- a/tapo_p100_control/switch.py
+++ b/tapo_p100_control/switch.py
@@ -84,6 +84,7 @@ class P100Plug(SwitchEntity):
         self._p100.login()
 
         data = self._p100.getDeviceInfo()
+        data = json.loads(data)
 
         encodedName = data["result"]["nickname"]
         name = b64decode(encodedName)

```
With the patch applied to tapo switch work as expected.
Marco

**Comment by fishbigger** [comment]
Can you give more info on the issue before you fixed it?

**Comment by veniplex** [comment]
I can confirm that I get the same error with the newest version of **Home Assistant Tapo P100 Control**. I am using **Home Assistant OS 2022.3.8** installed as VM (.ova) on a Synology NAS DS920+.

In the Home Assistant Logs I get the following error:
```
Logger: homeassistant.components.switch
Source: custom_components/tapo_p100_control/switch.py:83
Integration: Switch (documentation, issues)
First occurred: 19:57:24 (2 occurrences)
Last logged: 19:57:24

Error while setting up tapo_p100_control platform for switch
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.9/http/client.py", line 1377, in getresponse
    response.begin()
  File "/usr/local/lib/python3.9/http/client.py", line 320, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.9/http/client.py", line 281, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.9/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 451, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 340, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='192.168.178.46', port=80): Read timed out. (read timeout=2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/tapo_p100_control/switch.py", line 44, in setup_platform
    add_entities([P100Plug(p100)])
  File "/config/custom_components/tapo_p100_control/switch.py", line 53, in __init__
    self.update()
  File "/config/custom_components/tapo_p100_control/switch.py", line 83, in update
    self._p100.handshake()
  File "/usr/local/lib/python3.9/site-packages/PyP100/PyP100.py", line 122, in handshake
    r = self.session.post(URL, json=Payload, timeout=2)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 577, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 532, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='192.168.178.46', port=80): Read timed out. (read timeout=2)
```

I already tried to use an old commit of this repository (e.g. Oct 21 or Jan 22) but then I get a version incompatibility issue with Phyton.

I am trying to add multiple Tapo P100 Plugs. My `configuration.yaml` looks like this:

```
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Tapo Plugin for P100 Plugs
# Source: https://github.com/fishbigger/HomeAssistant-Tapo-P100-Control

# Tapo Plug 1
switch:
  - platform: tapo_p100_control
    ip_address: 192.168.x.x
    email: email@domain.com
    password: Password123!
    
# Tapo Plug 2
  - platform: tapo_p100_control
    ip_address: 192.168.x.x
    email: email@domain.com
    password: Password123!
    
# Tapo Plug 3
  - platform: tapo_p100_control
    ip_address: 192.168.x.x
    email: email@domain.com
    password: Password123!
    
# Tapo Plug 4
  - platform: tapo_p100_control
    ip_address: 192.168.x.x
    email: email@domain.com
    password: Password123!
    
# Tapo Plug 5
  - platform: tapo_p100_control
    ip_address: 192.168.x.x
    email: email@domain.com
    password: Password123!
    
# Tapo Plug 6
  - platform: tapo_p100_control
    ip_address: 192.168.x.x
    email: email@domain.com
    password: Password123!
```

Tapo P100 Plugs Hardware & Firmware:
- 2x Hardware `1.20.0` with Firmware `1.4.10 Build 20211104 Rel. 35882`
- 2x Hardware `1.0.0` with Firmware `1.3.6 Build 20210827 Rel. 37578`
- 1x Hardware `1.0.0` with Firmware `1.3.4 Build 20200925 Rel. 33922`
- 1x Hardware `1.0.0` with Firmware `1.3.3 Build 20200811 Rel. 52097`

Funny enough the Tapo iPhone App tells me all Plugs are up to date...

Does anyone know how to fix this issue?

**Comment by Budaa** [comment]
Hey, looks like a similar issue here, on the latest version, for lights and switch
```Error while setting up tapo_p100_control platform for light
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/tapo_p100_control/light.py", line 46, in setup_platform
    add_entities([L1510Bulb(l530)])
  File "/config/custom_components/tapo_p100_control/light.py", line 56, in __init__
    self.update()
  File "/config/custom_components/tapo_p100_control/light.py", line 100, in update
    self._l530.handshake()
  File "/usr/local/lib/python3.9/site-packages/PyP100/PyP100.py", line 124, in handshake
    encryptedKey = r.json()["result"]["key"]
KeyError: 'result'`
```

```
Logger: homeassistant.components.switch
Source: custom_components/tapo_p100_control/switch.py:83
Integration: Switch ([documentation](https://www.home-assistant.io/integrations/switch), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+switch%22))
First occurred: 17:18:34 (1 occurrences)
Last logged: 17:18:34

Error while setting up tapo_p100_control platform for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/tapo_p100_control/switch.py", line 44, in setup_platform
    add_entities([P100Plug(p100)])
  File "/config/custom_components/tapo_p100_control/switch.py", line 53, in __init__
    self.update()
  File "/config/custom_components/tapo_p100_control/switch.py", line 83, in update
    self._p100.handshake()
  File "/usr/local/lib/python3.9/site-packages/PyP100/PyP100.py", line 124, in handshake
    encryptedKey = r.json()["result"]["key"]
KeyError: 'result'
```

<img width="639" alt="Screenshot 2022-04-11 at 5 24 57 pm" src="https://user-images.githubusercontent.com/6993121/162786405-2cfc8b45-2777-44f4-a7c6-c028a543c3da.png">

**Comment by Budaa** [comment]
This solved the problem for me:
https://github.com/fishbigger/HomeAssistant-Tapo-P100-Control/issues/57#issuecomment-1097873717
