### ISSUE TITLE
JSON formatting error with L510 bulb

### ISSUE THREAD

**Issue by clakulus** [fishbigger/HomeAssistant-Tapo-P100-Control#50]
Hi. I am quite new to Home Assistant and have been trying out this integration with Tapo plugs and L510E bulb. With the bulb, I can turn it off, but when I attempt to turn it back on, I get the following error:

`Failed to call service light/turn_on. Error Code: -1003, JSON formatting error`

However, adjusting the brightness slider manually _will_ switch the bulb back on, just not the actual 'ON' switch.

Any help would be much appreciated.
Thanks

**Comment by djnaff** [comment]
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/tapo_p100_control/light.py:89
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 12:10:01 (3 occurrences)
Last logged: 12:10:18

[2782270104] Error Code: -1003, JSON formatting error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 186, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1538, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1575, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 203, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 665, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 898, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 702, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 504, in async_handle_light_on_service
    await light.async_turn_on(**filter_turn_on_params(light, params))
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 950, in async_turn_on
    await self.hass.async_add_executor_job(ft.partial(self.turn_on, **kwargs))
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/tapo_p100_control/light.py", line 89, in turn_on
    self._l530.setBrightness(newBrightness)
  File "/usr/local/lib/python3.9/site-packages/PyP100/PyL530.py", line 42, in setBrightness
    raise Exception(f"Error Code: {errorCode}, {errorMessage}")
Exception: Error Code: -1003, JSON formatting error 

I Have the same here is the log

**Comment by clakulus** [comment]
Yes, my log is similar. The brightness slider is also incorrect e.g. 50% brightness = 20% and so on.

**Comment by fishbigger** [comment]
Interesting. I have encountered the -1003 a few times but I can't remember how I fixed it. I won't have a chance to look at it until tomorrow but I will try and fix it then.

**Comment by Budaa** [comment]
Yes, same here. 
Failed to call service light/turn_on. Error Code: -1003, JSON formatting error

What's interesting is that I can turn off the bulb but turning it off returns the above error

**Comment by Budaa** [comment]
@fishbigger 
I think it's something related to parsing and formatting brightness levels.
Changing a method to this, fixes the issue:
```
    def turn_on(self, **kwargs) -> None:
        """Turn Plug On"""

        self._l530.turnOn()

        self._is_on = True
```
Do you know how can I debug the values of the newBrightness or kwargs.get?
Maybe there is a way to send the value as a notification to the home assistant dashboard?

**Comment by ghost** [comment]
Has anyone came across a fix for this yet? I've tried debugging myself, but I'm not exactly knowledgable with HA.

**Comment by fishbigger** [comment]
Apparently the pr #53 fixed this issue. Please can you download the latest version and see whether it worked?

**Comment by ghost** [comment]
> Apparently the pr #53 fixed this issue. Please can you download the latest version and see whether it worked?

Hi, that release does indeed fix the problem, apologies as I hadn't noticed it. Is it usual HA behaviour for the light to default to 100% whenever it is turned on though? Ideally, I would like it to default to the last set brightness if this could be done in any way? Thanks again.
