### ISSUE TITLE
KeyError result

### ISSUE THREAD

**Issue by icicimov** [fishbigger/HomeAssistant-Tapo-P100-Control#57]
Hi,

I have a single tapo P100 plug setup via tapo app. When trying to integrate to HA 2022.4.3:

```
switch:
  platform: tapo_p100_control
  ip_address: 192.168.x.x
  email: !secret tapo_user
  password: !secret tapo_password
```

I get this error in the log:

```
Logger: homeassistant.components.switch
Source: custom_components/tapo_p100_control/switch.py:83
Integration: Switch (documentation, issues)
First occurred: 14:53:23 (1 occurrences)
Last logged: 14:53:23

Error while setting up tapo_p100_control platform for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/tapo_p100_control/switch.py", line 44, in setup_platform
    add_entities([P100Plug(p100)])
  File "/config/custom_components/tapo_p100_control/switch.py", line 53, in __init__
    self.update()
  File "/config/custom_components/tapo_p100_control/switch.py", line 83, in update
    self._p100.handshake()
  File "/usr/local/lib/python3.9/site-packages/PyP100/PyP100.py", line 124, in handshake
    encryptedKey = r.json()["result"]["key"]
KeyError: 'result'
```

The plug is switched on and connected to the network via static IP and I can ping it from the hassio host. The device has `2.0` hardware version and firmware is `1.0.6 Build 210721 Rel.180949`

Thanks

**Comment by pgpais** [comment]
Having the same issue, but I have updated my firmware to ``1.4.10 Build 20211104 Rel. 35882``, thinking it could be a requirements, and it didn't solve it

**Comment by pgpais** [comment]
I was going through the already closed issues and found #36. It seemed to be a connection issue in their case, I will try the classic of turning off and on again later. (It is weird though, since I can see the plug from the Tapo app and Google Home app)

**Comment by icicimov** [comment]
Hmmm, not sure how can this be a connectivity issue at least not in my case. I can see the plug on my network and can ping its IP from the hassio host and other clients.

**Comment by pgpais** [comment]
Yes, it doesn't seem related to connectivity on my end either. I even reset the plug (just in case it was in a bugged state) and I still get the same error. I also have static IP configured.

**Comment by pgpais** [comment]
@icicimov as a workaround, try setting it up as an integration on the UI. I was just now able to do it

**Comment by Budaa** [comment]
Wow @pgpais it solved my issue here as well! Thanks! https://github.com/fishbigger/HomeAssistant-Tapo-P100-Control/issues/49#issuecomment-1095270673 

I'll just elaborate the workaround for other people. 
1. Go to Configuration
2. Click on a Devices & Services
3. Click "+ ADD INTEGRATION" in the bottom right corner
4. Search for "tapo"
5. Select Tapo Controller
6. Input your host, email and password (the same that you use in your tapo app)

Voila 🎉 


EDIT:
It looks like the integration that is showing up in the UI is this one:
https://github.com/petretiandrea/home-assistant-tapo-p100

**Comment by piffall** [comment]
Hi there, I have the same issue. 

I can provide some feedback about this issue.
* Underlying `PyP100` library works perfectly in the homeassistant environment.
* It's not a hardware issue.
* Bug affects HA 2022.4.x
* Probably this is caused by HA core upgrade.

I'm also a little bit confused about @Budaa [comment](https://github.com/fishbigger/HomeAssistant-Tapo-P100-Control/issues/57#issuecomment-1097873717). I checked for Tapo Controller Integration in UI, but I didn't find it. I also checked if this integration implements the `ConfigFlow` and it is not implemented.

**Comment by pgpais** [comment]
I was able to find the integration in the UI.
![image](https://user-images.githubusercontent.com/19236561/163172028-0b38d2f5-fb7a-461d-a0e6-0d0b84dc1de8.png)
Why would it show up for me and @Budaa then?

**Comment by piffall** [comment]
Very good question @pgpais . The only reason I can find, is that you are not using this integration.

**Comment by Budaa** [comment]
@piffall Good, point, I have this integration installed as well: https://github.com/petretiandrea/home-assistant-tapo-p100
Looks like it's this one indeed...
Line from manifest.json
```
"name": "Tapo Controller"
```
![Screenshot 2022-04-13 at 12 45 47 pm](https://user-images.githubusercontent.com/6993121/163173175-091d9fe6-95e8-4bce-b94d-f6b6ccd2ff02.png)

**Comment by pgpais** [comment]
Oh wow, do I feel dumb now. Apparently I had set up an add-on for tapo in HACS very long ago and forgot about it. 

I went into the custom components folder and you are indeed right, I have two there, one from HACS and this one.

I apologize for the confusion (could it be that the two conflict with each other?)

**Comment by piffall** [comment]
No conflict between both. This integration stopped working after 2022.4.x update, don't know exactly why. If you were using `tapo_p100_control` as platform, you were using actually this integration, and when you configured through UI, you started using the other one.

**Comment by icicimov** [comment]
Ok, let's clear up something here first. What I'm trying to add is a single standalone tapo plug no hub or coordinator etc. There is no tapo (only tp-link kasa one which device I do not have) integration under `Settings->Devices & Services->Integrations` in my case. I can see the `Tapo Controller` under `HACS->Integrations` which I just installed 

![tapo-hacs-integration](https://user-images.githubusercontent.com/16715091/163307335-3c92e731-df85-461c-9c14-1f353046795a.png)

and tried but got even uglier exception in the log with this one:

```
Logger: homeassistant.components.switch
Source: helpers/update_coordinator.py:164
Integration: Switch (documentation, issues)
First occurred: 12:57:41 (1 occurrences)
Last logged: 12:57:41

Error while setting up tapo platform for switch
Traceback (most recent call last):
  File "/config/custom_components/tapo/common_setup.py", line 96, in _update_with_fallback
    return await self.api.get_state()
  File "/usr/local/lib/python3.9/site-packages/plugp100/api.py", line 88, in get_state
    state=await self.get_state_as_dict(),
  File "/usr/local/lib/python3.9/site-packages/plugp100/api.py", line 212, in get_state_as_dict
    return await self._execute_method_request(device_info_method)
  File "/usr/local/lib/python3.9/site-packages/plugp100/api.py", line 224, in _execute_method_request
    dim_encrypted = self.tp_link_cipher.encrypt(jsons.dumps(method))
AttributeError: 'NoneType' object has no attribute 'encrypt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/tapo/common_setup.py", line 90, in _async_update_data
    return await self._update_with_fallback()
  File "/config/custom_components/tapo/common_setup.py", line 100, in _update_with_fallback
    return await self._update_with_fallback(False)
  File "/config/custom_components/tapo/common_setup.py", line 96, in _update_with_fallback
    return await self.api.get_state()
  File "/usr/local/lib/python3.9/site-packages/plugp100/api.py", line 89, in get_state
    energy_info=await self.get_energy_usage()
  File "/usr/local/lib/python3.9/site-packages/plugp100/api.py", line 217, in get_energy_usage
    await self._execute_method_request(GetEnergyUsageMethod(None))
  File "/usr/local/lib/python3.9/site-packages/plugp100/api.py", line 232, in _execute_method_request
    response = await self.http.async_make_post_cookie(f"{self.url}?token={self.token}", request_body,
  File "/usr/local/lib/python3.9/site-packages/plugp100/core/http_client.py", line 19, in async_make_post_cookie
    async with self.session.post(url, json=json, cookies=cookie) as response:
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 559, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 898, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
  File "/usr/local/lib/python3.9/site-packages/aiohttp/streams.py", line 616, in read
    await self._waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/tapo/common_setup.py", line 90, in _async_update_data
    return await self._update_with_fallback()
  File "/usr/local/lib/python3.9/site-packages/async_timeout/__init__.py", line 129, in __aexit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.9/site-packages/async_timeout/__init__.py", line 212, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 190, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/tapo/common_setup.py", line 92, in _async_update_data
    raise UpdateFailed() from exception
homeassistant.helpers.update_coordinator.UpdateFailed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/tapo/switch.py", line 28, in async_setup_platform
    coordinator = await setup_tapo_coordinator_from_dictionary(hass, config)
  File "/config/custom_components/tapo/common_setup.py", line 31, in setup_tapo_coordinator_from_dictionary
    return await setup_tapo_coordinator(
  File "/config/custom_components/tapo/common_setup.py", line 57, in setup_tapo_coordinator
    await coordinator.async_config_entry_first_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 164, in async_config_entry_first_refresh
    raise ex
homeassistant.exceptions.ConfigEntryNotReady
```
The config I used as per docs:
```
switch:
  platform: tapo
  host: 192.168.x.x
  username: !secret tapo_user
  password: !secret tapo_password
```
Note that again I do not see any tapo integration that I can configure under `Settings->Devices & Services->Integrations` so had to add the entity manually as shown above. Goes without saying that the things were done in proper order i.e. add the integration -> restart -> add the entity in the config yaml -> restart etc. There is no tapo Integration showing on the HA website either [Integrations](https://www.home-assistant.io/integrations/#all) so no idea how is this even an option for some people. Probably HA version diff.

P.S. I find it confusing wen people say "Integrations", please clarify what do you mean by that i.e. HA Integrations OR HACS Integrations (in which case we talking about `custom_components`)

**Comment by piffall** [comment]
Hi @icicimov 

Basically, many of you guys, have 2 different Tapo integrations setup in your `custom_components` directory. The platform called `tapo_p100_control` belongs to this repository and there is a bug since HA 2022.4.x release to be fixed. The other platform, called `tapo` belongs to another repository [https://github.com/petretiandrea/home-assistant-tapo-p100](https://github.com/petretiandrea/home-assistant-tapo-p100), which in its most recent version, is working without any issue and can be setup using the UI.

**Comment by icicimov** [comment]
@piffall yep the `tapo` one works now no idea why. I was adding a new Sonoff sensor to the config yaml and restarted HA as per usual and suddenly I got the P100 switch show up just like that.

UPDATE: Well it was of a short life, now after couple of additional HA restarts it shows as unavailable 
![P100-switch](https://user-images.githubusercontent.com/16715091/163356936-8d6afa86-e43c-4b0d-8c72-f28af71f2d58.png)
with message `This entity is currently unavailable and is an orphan to a removed, changed or dysfunctional integration or device.If the entity is no longer in use, you can clean it up by removing it.`

**Comment by veniplex** [comment]
> Hi @icicimov
> 
> Basically, many of you guys, have 2 different Tapo integrations setup in your `custom_components` directory. The platform called `tapo_p100_control` belongs to this repository and there is a bug since HA 2022.4.x release to be fixed. The other platform, called `tapo` belongs to another repository https://github.com/petretiandrea/home-assistant-tapo-p100, which in its most recent version, is working without any issue and can be setup using the UI.

Yeah it seems like HA itself did some changes so that this plugin is no longer working. Does anyone know if we can expect a working version any time soon?

**Comment by Tosiman-Global** [comment]
Guys, i had to comment line 92, 93, 94 
I think it might have to do something with login in twice to a switch.

**Comment by manuhakala98** [comment]
Same issue here:
`File "/usr/local/lib/python3.6/site-packages/PyP100/PyP100.py", line 130, in handshake
    encryptedKey = r.json()["result"]["key"]
KeyError: 'result'`

Any updates on this issue? I have tried to change whole user + hard resets. PyP100 v.0.1.2 and P100 build 1.2.1.
Also tried with different and simplier passwords.
